vim.g.symbols_outline = {
    -- highlight_hovered_item = true,
    -- show_guides = true,
    -- auto_preview = true,
    position = 'left',
    -- relative_width = true,
    width = 15,
    -- auto_close = false,
    show_numbers = true,
    -- show_relative_numbers = false,
    -- show_symbol_details = true,
    -- preview_bg_highlight = 'Pmenu',
    -- keymaps = { -- These keymaps can be a string or a table for multiple keys
    --     close = {"<Esc>", "q"},
    --     goto_location = "<Cr>",
    --     focus_location = "o",
    --     hover_symbol = "<C-space>",
    --     toggle_preview = "K",
    --     rename_symbol = "r",
    --     code_actions = "a",
    -- },
}
